# Use a imagem base do Node.js que já inclui npm
FROM node:14-alpine

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie o package.json e o package-lock.json para o diretório de trabalho
COPY package*.json ./

# Instale as dependências do projeto
RUN npm install

# Copie o restante do código do projeto para o diretório de trabalho
COPY . .

# Exponha a porta que o Express usará
EXPOSE 5000

# Comando para iniciar o servidor Express
CMD ["node", "server.js"]