# Use Node 18 base image
FROM node:18-alpine

WORKDIR /app

# Copy package.json and yarn.lock from the backend directory
COPY Backend/package.json Backend/yarn.lock ./

# Install dependencies
RUN if [ -f yarn.lock ]; then yarn install; else yarn install; fi

# Copy the rest of the backend directory
COPY Backend .

CMD ["node", "server.mjs"]