# Use uma imagem base com Node 18
FROM node:18-alpine

WORKDIR /app

# Copie os arquivos package.json e yarn.lock
COPY package.json yarn.lock ./

# Instale as dependências
RUN yarn install

# Instale o nodemon globalmente
RUN yarn global add nodemon

# Copie o restante do código
COPY . .

# Comando para iniciar a aplicação em modo watch
CMD ["yarn", "watch"]