# Use uma imagem base com Node 18
FROM node:18-alpine

WORKDIR /app

# Copie os arquivos package.json e yarn.lock
COPY package.json yarn.lock ./

# Instale as dependências
RUN yarn install

# Copie o restante do código
COPY . .

# Comando para iniciar a aplicação
CMD ["yarn", "start"]