version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.backend
    ports:
      - "4000:4000"
    volumes:
      - ../Backend:/app
      - /app/node_modules
      - ../Backend/Data:/app/Data
    environment:
      - NODE_ENV=development
    command: ["node", "server.mjs"]

  frontend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ../Frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development