# Use Node 18 base image
FROM node:18-alpine

WORKDIR /app

# Copy package.json and yarn.lock from the frontend directory
COPY Frontend/package.json Frontend/yarn.lock ./

# Install dependencies
RUN if [ -f yarn.lock ]; then yarn install; else yarn install; fi

# Copy the rest of the frontend directory
COPY Frontend .

# Expose the port the app runs on
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "dev", "watch"]