version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@database:5432/mydatabase
      - DATABASE_SSL=false
    ports:
      - "3000:3000"
    depends_on:
      - database

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "80:80"

  database:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: