version: '3.8'

services:
  db:
    build:
      context: ./Data
    environment:
      POSTGRES_USER: paulorezende877
      POSTGRES_PASSWORD: Lotus167
      POSTGRES_DB: dripstore
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./Backend/Dockerfile
    volumes:
      - ./Backend:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://paulorezende877:Lotus167@db:5432/dripstore
      DATABASE_SSL: "false"
    depends_on:
      - db
    command: ["sh", "-c", "/app/wait-for-it.sh db -- npm start"]

volumes:
  db-data: